<x-layouts::app :title="__('Dashboard')">
    @php($it = app()->getLocale() === 'it')
    <div class="pitmetric-app min-h-full w-full bg-pm-page px-3 py-4 sm:px-6 sm:py-5 lg:px-8 lg:py-7" data-demo-dashboard data-user="{{ auth()->id() }}" data-pm-mobile-dashboard>
        <div class="mx-auto w-full max-w-[1360px] space-y-4 sm:space-y-5">
            @if ($databaseAccessEnabled && ! $domainReady)
                <section class="pm-panel border-pm-warning/30 bg-pm-warning-subtle p-4 sm:p-5" role="status"><div class="flex items-start gap-3"><div class="grid size-9 shrink-0 place-items-center rounded-lg border border-pm-warning/30 bg-pm-warning-subtle text-sm font-black text-pm-warning">!</div><div><h2 class="font-bold text-pm-text">{{ $it ? 'Aggiornamento database richiesto' : 'Database update required' }}</h2><p class="mt-1 text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Il tuo account ha accesso ai dati reali, ma le nuove tabelle del core non sono ancora disponibili. Completa il deploy/migrazione prima di registrare sessioni.' : 'Your account has real database access, but the new core tables are not available yet. Complete the deployment/migration before recording sessions.' }}</p></div></div></section>
            @endif

            <section class="pm-panel p-5 sm:p-8"><div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div class="min-w-0"><div class="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-accent sm:text-xs sm:tracking-[0.14em]"><span class="pm-status-dot"></span>{{ $it ? 'Gestionale PitMetric' : 'PitMetric manager' }}</div><h1 class="mt-3 text-2xl font-black tracking-[-0.035em] text-pm-text sm:mt-4 sm:text-4xl">{{ $it ? 'Tutto il tuo motorsport in un unico posto.' : 'Your motorsport work, all in one place.' }}</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-pm-text-secondary sm:text-base sm:leading-7">{{ $databaseAccessEnabled ? ($it ? 'Il tuo account usa il database persistente PitMetric. Sessioni, utilizzo, manutenzione e costi restano sincronizzati sul server.' : 'Your account uses the persistent PitMetric database. Sessions, usage, maintenance and costs stay synchronized on the server.') : ($it ? 'Questa è la modalità locale di prova: i dati restano solo su questo browser finché l’account non viene attivato.' : 'This is local trial mode: data stays only in this browser until the account is activated.') }}</p></div><a href="{{ route('demo.sessions') }}" class="pm-race-button w-full shrink-0 sm:w-auto">{{ $it ? 'Registra sessione' : 'Record Session' }}</a></div></section>

            <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Mezzi' : 'Vehicles' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4" @if (! $databaseAccessEnabled) data-demo-count="vehicles" @endif>{{ $vehicleCount }}</p></article>
                <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Configurazioni' : 'Configurations' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4" @if (! $databaseAccessEnabled) data-demo-count="configurations" @endif>{{ $configurationCount }}</p></article>
                <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Sessioni' : 'Sessions' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4" @if (! $databaseAccessEnabled) data-demo-count="sessions" @endif>{{ $sessionCount }}</p></article>
                <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Interventi' : 'Maintenance' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4" @if (! $databaseAccessEnabled) data-demo-count="maintenance" @endif>{{ $maintenanceCount }}</p></article>
            </section>

            <section class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                @foreach ([['demo.garage','Garage',$it?'Gestisci i tuoi mezzi':'Manage your vehicles'],['demo.components',$it?'Componenti':'Components',$it?'Traccia utilizzo e usura':'Track usage and wear'],['demo.configurations',$it?'Configurazioni':'Configurations',$it?'Versiona build e componenti':'Version builds and components'],['demo.sessions',$it?'Sessioni':'Sessions',$it?'Registra attività in pista':'Record track activity'],['demo.circuits',$it?'Circuiti':'Circuits',$it?'Gestisci circuiti e layout':'Manage circuits and layouts'],['demo.maintenance',$it?'Manutenzione':'Maintenance',$it?'Intervalli e storico service':'Schedules and service history'],['demo.expenses',$it?'Spese':'Expenses',$it?'Controlla i costi':'Track costs'],['newsletter.edit','Newsletter',$it?'Gestisci le preferenze email':'Manage email preferences']] as [$routeName,$title,$subtitle])
                    <a href="{{ route($routeName) }}" class="group rounded-xl border border-pm-border bg-pm-surface p-4 transition hover:border-pm-border-strong hover:bg-pm-hover sm:p-5"><div class="flex items-center justify-between gap-3"><h2 class="min-w-0 font-bold text-pm-text">{{ $title }}</h2><span class="h-px w-5 shrink-0 bg-pm-border-strong transition-all group-hover:w-8 group-hover:bg-pm-accent"></span></div><p class="mt-2 text-sm text-pm-text-secondary">{{ $subtitle }}</p></a>
                @endforeach
            </section>
        </div>
    </div>
</x-layouts::app>
