<?php

return [
    'nav' => ['home' => 'Home','updates' => 'Updates','about' => 'About','dashboard' => 'Dashboard','login' => 'Log in'],
    'home' => [
        'eyebrow' => 'Motorsport data, without the noise','title_1' => 'Know every lap.','title_2' => 'Track every component.','intro' => 'PitMetric is motorsport software built for drivers, owners and small teams who want a reliable picture of what is installed, how much it has worked and what needs attention next.','open_dashboard' => 'Open dashboard','discover' => 'Discover PitMetric','track_note_label' => 'Built around history','track_note' => 'A session points to the exact configuration used at that moment. Replacing a component tomorrow never rewrites yesterday.','hero_image_alt' => 'Race car on track at Monza','garage_image_alt' => 'Race cars and mechanics inside a motorsport garage','configuration' => 'Configuration','configuration_copy' => 'Record the physical build of the vehicle and the components actually installed.','usage' => 'Usage','usage_copy' => 'Track distance, runtime, cycles, sessions and events without forcing every component into kilometres.','maintenance' => 'Maintenance','maintenance_copy' => 'Connect real usage with inspection, rebuild and replacement intervals.','costs' => 'Costs','costs_copy' => 'Keep a clear view of expenses, interventions and the real operating cost of the vehicle.','principle_label' => 'The principle','principle_title' => 'History must stay true.','principle_copy' => 'PitMetric is being designed around immutable technical history. When a session is recorded, it keeps the exact configuration used at that time. Change the engine, chain or tyres later and previous sessions remain untouched.','propagation' => 'Usage propagated only to compatible component trackers','roadmap' => 'Product direction','roadmap_title' => 'Built for real work at the track.','follow_updates' => 'Follow development updates →','roadmap_1_title' => 'Vehicle & configuration history','roadmap_1_copy' => 'Versioned configuration snapshots preserve the technical history of every session.','roadmap_2_title' => 'Multi-metric component tracking','roadmap_2_copy' => 'Distance, hours, cycles, sessions and events with independent rules.','roadmap_3_title' => 'Circuit-driven usage','roadmap_3_copy' => 'Layout length × laps can generate verified usage automatically.'
    ],
    'about' => [
        'title' => 'About','description' => 'Simone Butticè, Junior Full-Stack Web Developer and creator of PitMetric.','creator' => 'Creator / Developer','image_alt' => 'Racing cockpit and steering wheel detail','role' => 'Junior Full-Stack Web Developer with hands-on experience building custom web management applications using PHP, JavaScript and MySQL. My work focuses on relational database architecture, application logic and turning functional requirements into practical software.','stack_label' => 'Technical stack','backend' => 'Backend','frontend' => 'Frontend','database' => 'Database','mobile_tools' => 'Mobile & tools','experience' => 'Experience','present' => 'Sep 2024 — Present','experience_copy' => 'At Edisoft I work on custom web management applications, API integrations, relational databases and existing PHP systems. The role includes both new development and maintenance of complex legacy software.','exp_1' => 'Build PHP, JavaScript, HTML, CSS and MySQL management applications.','exp_2' => 'Design relational databases from scratch and extend legacy models with 100+ tables.','exp_3' => 'Translate functional requirements into data models, flows and application logic.','exp_4' => 'Build REST-style PHP endpoints with JSON, token authentication and database integration.','exp_5' => 'Develop API-driven Ionic applications connected to PHP backends.','exp_6' => 'Debug legacy software and optimise slow SQL queries and complex pages.','education' => 'Education','diploma' => 'IT Technical Diploma — Computer Science','languages' => 'Languages','native' => 'Native','professional' => 'Professional working proficiency','why' => 'Why PitMetric','why_title' => 'A personal project designed like a real product.','why_copy' => 'PitMetric is where I combine my experience with management software, relational data and APIs with a genuine interest in motorsport. The goal is not to make another generic dashboard, but a tool that can preserve technical history and make component usage understandable.','interests' => 'Interests','interests_copy' => 'Chess & strategy · Video editing · Audiovisual content · Motorsport'
    ],
    'updates' => ['title' => 'Updates','description' => 'Development updates from PitMetric.','label' => 'Development log','intro' => 'Product decisions, technical progress and notes from building PitMetric.','read' => 'Read update →','empty' => 'No updates have been published yet. The devlog is coming soon.','back' => '← All updates'],
    'dashboard' => [
        'eyebrow' => 'PitMetric workspace','welcome' => 'Your motorsport data starts here.','intro' => 'The operational core is being built around vehicles, configuration history, component usage and maintenance. This dashboard will become the fastest way to understand what needs attention.','vehicle' => 'Vehicle','vehicle_value' => 'No vehicle yet','configuration' => 'Current configuration','configuration_value' => 'Not configured','usage' => 'Recorded usage','usage_value' => 'No sessions yet','maintenance' => 'Maintenance status','maintenance_value' => 'No active alerts','next_title' => 'Next useful step','next_copy' => 'Create the first vehicle and start building a configuration with the components you actually want to track.','roadmap_title' => 'Core workflow','roadmap_1' => 'Vehicle & components','roadmap_2' => 'Configuration snapshots','roadmap_3' => 'Sessions & usage','roadmap_4' => 'Maintenance & costs'
    ],
    'footer' => ['tagline' => 'Built for better decisions between laps.','cookies' => 'Cookie settings','photo_note' => 'Editorial motorsport photography from Unsplash.'],
    'language' => ['title' => 'Choose your language','copy' => 'PitMetric is available in English and Italian. English is the default and you can change it at any time.','english' => 'English','italian' => 'Italiano'],
    'cookies' => ['title' => 'Cookie preferences','copy' => 'PitMetric currently uses only cookies required for the site to work and preference cookies such as your language choice. Analytics and advertising cookies are not currently loaded.','necessary' => 'Necessary only','accept' => 'Accept preferences','settings' => 'Cookie settings','policy_title' => 'Cookies on PitMetric','policy_copy' => 'PitMetric currently uses technical cookies needed for authentication, security and core site functions, plus preference cookies for language and consent. No analytics or advertising cookies are currently active.','necessary_title' => 'Necessary cookies','necessary_copy' => 'Used for security, sessions, authentication and essential Laravel/PitMetric functionality. These cannot be disabled while using the site.','preferences_title' => 'Preference cookies','preferences_copy' => 'Used to remember choices such as your preferred language and cookie-consent state.','optional_title' => 'Analytics and marketing','optional_copy' => 'Not currently used. If PitMetric adds them in the future, they should remain disabled until you consent.','back' => 'Back to PitMetric'],
];
