<aside class="space-y-5">
    <section class="pm-panel p-5">
        <div class="flex items-end justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-accent">READINESS</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $it ? 'Stato manutenzione' : 'Maintenance state' }}</h2></div><a href="{{ route('maintenance.index') }}" class="text-xs font-bold text-pm-accent hover:underline">{{ $it ? 'Apri' : 'Open' }}</a></div>
        <div class="mt-4 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">{{ $maintenanceSummary['ok'] }}</p><p class="mt-1 text-[10px] font-bold uppercase text-pm-muted">OK</p></div><div class="rounded-xl border border-pm-warning/25 bg-pm-warning-subtle p-3"><p class="text-xl font-black text-pm-warning">{{ $maintenanceSummary['due_soon'] }}</p><p class="mt-1 text-[10px] font-bold uppercase text-pm-warning">Soon</p></div><div class="rounded-xl border border-pm-danger/25 bg-pm-danger-subtle p-3"><p class="text-xl font-black text-pm-danger">{{ $maintenanceSummary['overdue'] }}</p><p class="mt-1 text-[10px] font-bold uppercase text-pm-danger">Overdue</p></div></div>
        <div class="mt-4 space-y-2">
            @forelse ($attentionMaintenance as $schedule)
                @php($state = $maintenanceStates[$schedule->id] ?? null)
                <div class="rounded-xl border border-pm-warning/25 bg-pm-warning-subtle p-3"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-pm-text">{{ $schedule->tracker->component->name }}</p><p class="mt-1 text-xs text-pm-muted">{{ $schedule->name }}</p></div><x-pitmetric.status-badge :label="$state['status'] ?? 'untracked'" :variant="($state['status'] ?? '') === 'overdue' ? 'danger' : 'warning'" /></div>@if ($state)<p class="mt-2 text-xs text-pm-text-secondary">{{ $it ? 'Utilizzo dal service' : 'Usage since service' }}: {{ $formatUsage((int) $state['used'], $schedule->tracker->metric) }}</p>@endif</div>
            @empty
                <p class="rounded-xl border border-pm-success/20 bg-pm-success-subtle p-3 text-sm font-semibold text-pm-success">{{ $it ? 'Nessun componente delle entry richiede attenzione.' : 'No entry component currently needs attention.' }}</p>
            @endforelse
        </div>
    </section>

    <section class="pm-panel p-5">
        <div class="flex items-end justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-accent">{{ $it ? 'LAVORI' : 'WORK' }}</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $it ? 'Task del weekend' : 'Weekend tasks' }}</h2></div>
            @if ($canWrite)<x-crud-modal id="add-event-task" :title="$it ? 'Nuovo lavoro' : 'New task'" :trigger="$it ? '+ Lavoro' : '+ Task'" trigger-class="pm-ghost-button">@can('team-write')<form method="POST" action="{{ route('events.tasks.store', $event) }}" class="grid gap-4">@csrf<label class="grid gap-2"><span class="pm-label">{{ $it ? 'Titolo' : 'Title' }}</span><input class="pm-input" name="title" maxlength="160" required></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-2"><span class="pm-label">Priority</span><select class="pm-input" name="priority"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="critical">Critical</option></select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Assegnazione' : 'Assignment' }}</span><select class="pm-input" name="event_entry_id"><option value="">Team</option>@foreach ($event->entries as $entry)<option value="{{ $entry->id }}">{{ $entry->driver->display_name }} / {{ $entry->vehicle->name }}</option>@endforeach</select></label></div><label class="grid gap-2"><span class="pm-label">Due</span><input class="pm-input" type="datetime-local" name="due_at"></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Dettagli' : 'Details' }}</span><textarea class="pm-input min-h-20" name="description" maxlength="3000"></textarea></label><div class="flex justify-end"><button class="pm-race-button" type="submit">{{ $it ? 'Aggiungi' : 'Add' }}</button></div></form>@endcan</x-crud-modal>@endif
        </div>
        <div class="mt-5 space-y-2">
            @forelse ($sortedTasks as $task)
                <div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-pm-text {{ $task->status === 'done' ? 'line-through opacity-60' : '' }}">{{ $task->title }}</p><p class="mt-1 text-xs text-pm-muted">{{ ucfirst($task->priority) }}{{ $task->eventEntry ? ' · '.$task->eventEntry->driver->display_name : '' }}{{ $task->due_at ? ' · '.$task->due_at->format('d/m H:i') : '' }}</p></div><x-pitmetric.status-badge :label="$task->status" :variant="$task->status === 'done' ? 'success' : ($task->priority === 'critical' ? 'danger' : ($task->priority === 'high' ? 'warning' : 'neutral'))" /></div>
                    @if ($canWrite)<div class="mt-3"><x-pitmetric.record-editor id="edit-task-{{ $task->id }}" :title="$it ? 'Modifica attività' : 'Edit task'" :action="route('events.tasks.details', $task)">
                        <label class="grid gap-2"><span class="pm-label">{{ $it ? 'Titolo' : 'Title' }}</span><input class="pm-input" name="title" type="text" value="{{ $task->title }}" required maxlength="160"></label>
                        <label class="grid gap-2"><span class="pm-label">{{ $it ? 'Priorità' : 'Priority' }}</span><select class="pm-input" name="priority">@foreach (['low' => ($it ? 'Bassa' : 'Low'), 'normal' => ($it ? 'Normale' : 'Normal'), 'high' => ($it ? 'Alta' : 'High'), 'critical' => ($it ? 'Critica' : 'Critical')] as $value => $label)<option value="{{ $value }}" @selected($task->priority === $value)>{{ $label }}</option>@endforeach</select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Scadenza' : 'Due' }}</span><input class="pm-input" name="due_at" type="datetime-local" value="{{ $task->due_at?->format('Y-m-d\TH:i') }}"></label>
                        <label class="grid gap-2"><span class="pm-label">{{ $it ? 'Iscrizione' : 'Entry' }}</span><select class="pm-input" name="event_entry_id"><option value="">{{ $it ? 'Tutto il team' : 'Whole team' }}</option>@foreach ($event->entries as $candidateEntry)<option value="{{ $candidateEntry->id }}" @selected($task->event_entry_id === $candidateEntry->id)>{{ $candidateEntry->driver->display_name }} · {{ $candidateEntry->vehicle->name }}</option>@endforeach</select></label><label class="grid gap-2 sm:col-span-2"><span class="pm-label">Note</span><textarea class="pm-input min-h-24" name="description" maxlength="3000">{{ $task->description }}</textarea></label>
                    </x-pitmetric.record-editor><x-pitmetric.record-delete :action="route('events.tasks.destroy', $task)" />
                    <x-crud-modal id="update-task-{{ $task->id }}" :title="$it ? 'Aggiorna lavoro' : 'Update task'" :description="$task->title" :trigger="$it ? 'Aggiorna' : 'Update'" trigger-class="text-xs font-bold text-pm-accent hover:underline">@can('team-write')<form method="POST" action="{{ route('events.tasks.update', $task) }}" class="grid gap-4">@csrf @method('PATCH')<label class="grid gap-2"><span class="pm-label">Status</span><select class="pm-input" name="status"><option value="todo" @selected($task->status === 'todo')>Todo</option><option value="in_progress" @selected($task->status === 'in_progress')>In progress</option><option value="done" @selected($task->status === 'done')>Done</option></select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Costo completamento (€)' : 'Completion cost (€)' }}</span><input class="pm-input" name="operation_cost" type="number" min="0" max="1000000" step="0.01"></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Descrizione costo' : 'Cost description' }}</span><input class="pm-input" name="cost_description" maxlength="180" placeholder="{{ $task->title }}"></label><div class="flex justify-end"><button class="pm-race-button" type="submit">{{ $it ? 'Salva' : 'Save' }}</button></div></form>@endcan</x-crud-modal></div>@endif
                </div>
            @empty<p class="text-sm text-pm-muted">{{ $it ? 'Nessun lavoro aperto.' : 'No tasks yet.' }}</p>@endforelse
        </div>
    </section>

    <section class="pm-panel p-5">
        <div class="flex items-end justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-muted">LOG</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $it ? 'Diario Trackside' : 'Trackside log' }}</h2></div>
            @if ($canWrite)<x-crud-modal id="add-event-note" :title="$it ? 'Aggiungi nota' : 'Add note'" :trigger="$it ? '+ Nota' : '+ Note'" trigger-class="pm-ghost-button">@can('team-write')<form method="POST" action="{{ route('events.notes.store', $event) }}" class="grid gap-4">@csrf<label class="grid gap-2"><span class="pm-label">{{ $it ? 'Tipo nota' : 'Note type' }}</span><select class="pm-input" name="kind" required><option value="technical">{{ $it ? 'Tecnica' : 'Technical' }}</option><option value="driver_feedback">{{ $it ? 'Feedback pilota' : 'Driver feedback' }}</option><option value="incident">{{ $it ? 'Incidente' : 'Incident' }}</option><option value="operations">{{ $it ? 'Operazioni' : 'Operations' }}</option></select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Nota' : 'Note' }}</span><textarea class="pm-input min-h-28" name="body" maxlength="5000" required></textarea></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Riferimento' : 'Reference' }}</span><select class="pm-input" name="event_entry_id"><option value="">{{ $it ? 'Generale' : 'General' }}</option>@foreach ($event->entries as $entry)<option value="{{ $entry->id }}">{{ $entry->driver->display_name }}</option>@endforeach</select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Data e ora' : 'Date and time' }}</span><input class="pm-input" type="datetime-local" name="occurred_at" required value="{{ now()->format('Y-m-d\TH:i') }}"></label></div><div class="flex justify-end"><button class="pm-race-button" type="submit">{{ $it ? 'Aggiungi nota' : 'Add note' }}</button></div></form>@endcan</x-crud-modal>@endif
        </div>
        <div class="mt-5 space-y-2">@forelse ($sortedNotes as $note)<div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><div class="flex flex-wrap items-center gap-2"><span class="text-[10px] font-black uppercase tracking-[0.12em] text-pm-accent">{{ $noteLabels[$note->kind] ?? ucfirst($note->kind) }}</span><span class="text-xs text-pm-muted">{{ $note->occurred_at->format('d/m H:i') }}{{ $note->eventEntry ? ' · '.$note->eventEntry->driver->display_name : '' }}</span></div><p class="mt-2 text-sm leading-6 text-pm-text-secondary">{{ $note->body }}</p><div class="pm-record-actions"><x-pitmetric.record-editor id="edit-note-{{ $note->id }}" :title="$it ? 'Modifica nota' : 'Edit note'" :action="route('events.notes.update', $note)">
            <label class="grid gap-2"><span class="pm-label">{{ $it ? 'Tipo' : 'Type' }}</span><select class="pm-input" name="kind">@foreach ($noteLabels as $value => $label)<option value="{{ $value }}" @selected($note->kind === $value)>{{ $label }}</option>@endforeach</select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Data e ora' : 'Date and time' }}</span><input class="pm-input" name="occurred_at" type="datetime-local" value="{{ $note->occurred_at?->format('Y-m-d\TH:i') }}" required></label>
            <label class="grid gap-2"><span class="pm-label">{{ $it ? 'Iscrizione' : 'Entry' }}</span><select class="pm-input" name="event_entry_id"><option value="">{{ $it ? 'Tutto il team' : 'Whole team' }}</option>@foreach ($event->entries as $candidateEntry)<option value="{{ $candidateEntry->id }}" @selected($note->event_entry_id === $candidateEntry->id)>{{ $candidateEntry->driver->display_name }} · {{ $candidateEntry->vehicle->name }}</option>@endforeach</select></label><label class="grid gap-2 sm:col-span-2"><span class="pm-label">Note</span><textarea class="pm-input min-h-24" name="body" maxlength="5000">{{ $note->body }}</textarea></label>
        </x-pitmetric.record-editor><x-pitmetric.record-delete :action="route('events.notes.destroy', $note)" /></div></div>@empty<p class="text-sm text-pm-muted">{{ $it ? 'Nessuna nota.' : 'No notes yet.' }}</p>@endforelse</div>
    </section>

    <section class="pm-panel p-5">
        <div class="flex items-end justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'COSTI' : 'COSTS' }}</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $it ? 'Spese evento' : 'Event expenses' }}</h2></div><div class="text-right"><p class="text-xl font-black text-pm-text">€ {{ number_format($eventSpend / 100, 2, ',', '.') }}</p>@if ($canWrite)<x-crud-modal id="add-event-expense" :title="$it ? 'Spesa manuale' : 'Manual expense'" :trigger="$it ? '+ Spesa' : '+ Expense'" trigger-class="mt-2 text-xs font-bold text-pm-accent hover:underline">@can('team-write')<form method="POST" action="{{ route('events.expenses.store', $event) }}" class="grid gap-4 sm:grid-cols-2">@csrf<label class="grid gap-2"><span class="pm-label">{{ $it ? 'Importo (€)' : 'Amount (€)' }}</span><input class="pm-input" type="number" name="amount" min="0.01" max="1000000" step="0.01" required></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Categoria' : 'Category' }}</span><input class="pm-input" name="category" maxlength="80" required></label><label class="grid gap-2 sm:col-span-2"><span class="pm-label">{{ $it ? 'Descrizione' : 'Description' }}</span><input class="pm-input" name="description" maxlength="180" required></label><label class="grid gap-2 sm:col-span-2"><span class="pm-label">{{ $it ? 'Data e ora' : 'Date and time' }}</span><input class="pm-input" type="datetime-local" name="occurred_at" required value="{{ now()->format('Y-m-d\TH:i') }}"></label><div class="flex justify-end sm:col-span-2"><button class="pm-race-button" type="submit">{{ $it ? 'Registra' : 'Record' }}</button></div></form>@endcan</x-crud-modal>@endif</div></div>
        <div class="mt-5 space-y-2">@forelse ($sortedExpenses->take(8) as $expense)<div class="flex items-start justify-between gap-3 rounded-xl border border-pm-border bg-pm-subtle p-3"><div><p class="font-bold text-pm-text">{{ $expense->description }}</p><p class="mt-1 text-xs text-pm-muted">{{ $expense->occurred_at->format('d/m H:i') }} · {{ ucfirst(str_replace('_', ' ', $expense->category)) }}{{ $expense->related_type ? ' · Auto linked' : '' }}</p></div><span class="font-mono text-sm font-bold text-pm-text">€ {{ number_format($expense->amount_cents / 100, 2, ',', '.') }}</span></div>@empty<p class="text-sm text-pm-muted">{{ $it ? 'Nessuna spesa.' : 'No expenses yet.' }}</p>@endforelse</div>
    </section>
</aside>
