<?php

use App\Models\Circuit;
use App\Models\Component;
use App\Models\ComponentTracker;
use App\Models\ComponentType;
use App\Models\Configuration;
use App\Models\Expense;
use App\Models\MaintenanceSchedule;
use App\Models\Session;
use App\Models\UsageMetricType;
use App\Models\User;
use App\Models\Vehicle;
use App\Services\CreateConfigurationVersionService;

it('links component purchase cost to the expense ledger', function () {
    $user = User::factory()->withDatabaseAccess()->create();

    $this->actingAs($user)
        ->post(route('components.store'), [
            'name' => 'Engine #02',
            'type_name' => 'Engine',
            'metric_key' => 'runtime',
            'serial_number' => 'ENG-002',
            'purchase_date' => '2026-09-14',
            'purchase_cost' => '899.90',
        ])
        ->assertRedirect(route('demo.components'));

    $component = Component::query()->where('name', 'Engine #02')->firstOrFail();
    $expense = Expense::query()
        ->where('related_type', 'component')
        ->where('related_id', $component->id)
        ->firstOrFail();

    expect($component->purchase_cost_cents)->toBe(89990)
        ->and($expense->amount_cents)->toBe(89990)
        ->and($expense->category)->toBe('parts');
});

it('records a session once, links its cost and raises maintenance attention from usage', function () {
    $user = User::factory()->withDatabaseAccess()->create();
    $workspace = $user->workspaces()->firstOrFail();
    $this->actingAs($user);

    $vehicle = Vehicle::factory()->create(['workspace_id' => $workspace->id, 'name' => 'Kart #46']);
    $type = ComponentType::create(['name' => 'Chain']);
    $component = Component::create(['component_type_id' => $type->id, 'name' => 'Chain #46', 'status' => 'active']);
    $metric = UsageMetricType::query()->where('key', 'distance')->firstOrFail();
    $tracker = ComponentTracker::create([
        'component_id' => $component->id,
        'usage_metric_type_id' => $metric->id,
        'is_active' => true,
    ]);

    $configuration = Configuration::create([
        'vehicle_id' => $vehicle->id,
        'name' => 'Race setup',
        'status' => 'active',
    ]);
    $version = app(CreateConfigurationVersionService::class)->create($configuration, $user, [$component->id]);

    $circuit = Circuit::create(['name' => 'Workflow Circuit']);
    $layout = $circuit->layouts()->create([
        'name' => 'Full',
        'length_meters' => 1000,
        'is_active' => true,
    ]);

    MaintenanceSchedule::create([
        'component_tracker_id' => $tracker->id,
        'name' => 'Chain replacement',
        'interval_value' => 10000,
        'warning_value' => 2000,
        'is_active' => true,
    ]);

    $response = $this->post(route('sessions.store'), [
        'configuration_version_id' => $version->id,
        'circuit_layout_id' => $layout->id,
        'session_type' => 'practice',
        'started_at' => '2026-09-14 12:00:00',
        'completed_laps' => 10,
        'duration_minutes' => 20,
        'session_cost' => '75.50',
        'cost_description' => 'Track fee',
    ]);

    $session = Session::query()->firstOrFail();
    $expense = Expense::query()
        ->where('related_type', 'session')
        ->where('related_id', $session->id)
        ->firstOrFail();

    $response
        ->assertRedirect(route('demo.sessions', ['recorded' => $session->id]))
        ->assertSessionHas('maintenance_attention', 1);

    expect($session->status)->toBe('finalized')
        ->and((int) $tracker->usageEntries()->sum('value'))->toBe(10000)
        ->and($expense->amount_cents)->toBe(7550)
        ->and($expense->description)->toBe('Track fee');

    $this->get(route('dashboard'))
        ->assertOk()
        ->assertSee('Needs attention')
        ->assertSee('75,50');
});

it('prevents deleting an expense generated by an operational source', function () {
    $user = User::factory()->withDatabaseAccess()->create();
    $this->actingAs($user);

    $expense = Expense::create([
        'amount_cents' => 2500,
        'currency' => 'EUR',
        'category' => 'track',
        'description' => 'Linked fee',
        'occurred_at' => now(),
        'related_type' => 'session',
        'related_id' => 99,
        'created_by' => $user->id,
    ]);

    $this->delete(route('expenses.destroy', $expense))
        ->assertRedirect(route('demo.expenses'))
        ->assertSessionHas('error');

    expect($expense->fresh())->not->toBeNull();
});
