<x-layouts::app :title="__('Expenses')">
    @php($it = app()->getLocale() === 'it')
    <div class="pitmetric-app min-h-full w-full bg-pm-page px-4 py-5 sm:px-6 lg:px-8 lg:py-7">
        <div class="mx-auto w-full max-w-[1360px] space-y-5">
            <div><p class="text-[11px] font-bold uppercase tracking-[0.14em] text-pm-accent">EXPENSES</p><x-pitmetric.page-header :title="$it ? 'Costi reali' : 'Real costs'" :description="$it ? 'Registra costi persistenti del tuo programma motorsport. Gli importi sono salvati in centesimi per evitare errori di arrotondamento.' : 'Record persistent motorsport costs. Amounts are stored as integer cents to avoid rounding errors.'" /></div>
            @if (session('status'))<div class="rounded-xl border border-pm-success/25 bg-pm-success-subtle px-4 py-3 text-sm font-semibold text-pm-success">{{ session('status') }}</div>@endif
            @if ($errors->any())<div class="rounded-xl border border-pm-danger/30 bg-pm-danger-subtle p-4 text-sm text-pm-danger"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

            <section class="grid gap-4 lg:grid-cols-[1fr_280px]">
                <div class="pm-panel p-5 sm:p-6"><form method="POST" action="{{ route('expenses.store') }}" class="grid gap-4 sm:grid-cols-2">@csrf<label class="grid gap-2"><span class="pm-label">{{ $it ? 'Importo (€)' : 'Amount (€)' }}</span><input class="pm-input" name="amount" type="number" required min="0.01" max="1000000" step="0.01"></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Categoria' : 'Category' }}</span><select class="pm-input" name="category" required><option value="maintenance">Maintenance</option><option value="parts">Parts</option><option value="fuel">Fuel</option><option value="tyres">Tyres</option><option value="track">Track</option><option value="travel">Travel</option><option value="other">Other</option></select></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Data e ora' : 'Date and time' }}</span><input class="pm-input" name="occurred_at" type="datetime-local" required></label><label class="grid gap-2"><span class="pm-label">{{ $it ? 'Descrizione' : 'Description' }}</span><input class="pm-input" name="description" required maxlength="180"></label><div class="sm:col-span-2"><button class="pm-race-button" type="submit">{{ $it ? 'Registra spesa' : 'Record expense' }}</button></div></form></div>
                <article class="pm-panel p-5 sm:p-6"><p class="text-[11px] font-bold uppercase tracking-[0.1em] text-pm-muted">{{ $it ? 'Totale registrato' : 'Recorded total' }}</p><p class="mt-4 text-3xl font-black text-pm-text">€ {{ number_format($totalCents / 100, 2, ',', '.') }}</p><p class="mt-2 text-sm text-pm-text-secondary">{{ $expenses->count() }} {{ $it ? 'voci di costo' : 'cost entries' }}</p></article>
            </section>

            <section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">{{ $it ? 'Data' : 'Date' }}</th><th class="px-4 py-3">{{ $it ? 'Categoria' : 'Category' }}</th><th class="px-4 py-3">{{ $it ? 'Descrizione' : 'Description' }}</th><th class="px-4 py-3 text-right">{{ $it ? 'Importo' : 'Amount' }}</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-pm-border">@forelse ($expenses as $expense)<tr><td class="px-4 py-4 text-pm-text-secondary">{{ $expense->occurred_at->format('d/m/Y') }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ ucfirst($expense->category) }}</td><td class="px-4 py-4 font-semibold text-pm-text">{{ $expense->description }}</td><td class="px-4 py-4 text-right font-mono font-bold text-pm-text">€ {{ number_format($expense->amount_cents / 100, 2, ',', '.') }}</td><td class="px-4 py-4 text-right"><form method="POST" action="{{ route('expenses.destroy', $expense) }}" onsubmit="return confirm(@js($it ? 'Eliminare questa spesa?' : 'Delete this expense?'))">@csrf @method('DELETE')<button class="text-xs font-bold text-pm-danger hover:underline">{{ $it ? 'Elimina' : 'Delete' }}</button></form></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-sm text-pm-muted">{{ $it ? 'Nessuna spesa registrata.' : 'No expenses recorded.' }}</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
</x-layouts::app>
