<x-layouts::app_demo :title="$title" :section="$section">
    @php
        $it = app()->getLocale() === 'it';
        $demoUrl = fn (string $target) => $target === 'dashboard'
            ? route('demo.public')
            : route('demo.manager', ['section' => $target]);
        $readonly = $it ? 'Demo sola lettura' : 'Read-only demo';
    @endphp

    <div class="pitmetric-app min-h-full w-full bg-pm-page px-4 py-5 sm:px-6 lg:px-8 lg:py-7" data-pm-page-content>
        <div class="mx-auto w-full max-w-[1360px] space-y-5">
            @if ($section === 'dashboard')
                <section class="pm-panel p-5 sm:p-8" data-pm-dashboard-next>
                    <div class="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
                        <div class="min-w-0">
                            <div class="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-accent sm:text-xs sm:tracking-[0.14em]"><span class="pm-status-dot"></span>{{ $it ? 'Prossima azione operativa' : 'Next operational action' }}</div>
                            <h1 class="mt-3 text-2xl font-black tracking-[-0.035em] text-pm-text sm:mt-4 sm:text-4xl">{{ $it ? 'Prepara il prossimo race weekend' : 'Prepare the next race weekend' }}</h1>
                            <p class="mt-3 max-w-3xl text-sm leading-6 text-pm-text-secondary sm:text-base sm:leading-7">{{ $it ? 'La base tecnica è pronta. Apri il weekend gara e verifica entry, sessioni, task, note e costi.' : 'The technical base is ready. Open the race weekend and review entries, sessions, tasks, notes and costs.' }}</p>
                        </div>
                        <a href="{{ $demoUrl('events') }}" class="pm-race-button w-full shrink-0 sm:w-auto">{{ $it ? 'Apri race weekend' : 'Open race weekend' }}</a>
                    </div>
                </section>

                <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                    <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Mezzi' : 'Vehicles' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4">{{ count($demo['vehicles']) }}</p></article>
                    <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Configurazioni' : 'Configurations' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4">{{ count($demo['configurations']) }}</p></article>
                    <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Sessioni' : 'Sessions' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4">18</p></article>
                    <article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Interventi' : 'Maintenance' }}</p><p class="mt-3 text-3xl font-black text-pm-text sm:mt-4">{{ count($demo['maintenance']) }}</p></article>
                </section>

                <section class="pm-panel overflow-hidden">
                    <div class="grid gap-5 p-5 sm:p-6 xl:grid-cols-[1fr_auto] xl:items-center">
                        <div class="min-w-0">
                            <div class="flex flex-wrap items-center gap-2"><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-accent">{{ $it ? 'WEEKEND IN CORSO' : 'ACTIVE WEEKEND' }}</p><x-pitmetric.status-badge label="active" variant="success" /></div>
                            <h2 class="mt-2 text-2xl font-black text-pm-text">Busca Race Weekend</h2>
                            <p class="mt-2 text-sm text-pm-text-secondary">24/09/2026 - 25/09/2026 · Circuito di Busca · Full</p>
                        </div>
                        <div class="flex flex-col gap-3 sm:flex-row sm:items-center">
                            <div class="grid grid-cols-3 gap-2 text-center sm:min-w-[300px]">
                                <div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">2</p><p class="mt-1 text-[10px] uppercase text-pm-muted">Entries</p></div>
                                <div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">4</p><p class="mt-1 text-[10px] uppercase text-pm-muted">Sessions</p></div>
                                <div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">6</p><p class="mt-1 text-[10px] uppercase text-pm-muted">Tasks</p></div>
                            </div>
                            <a href="{{ $demoUrl('events') }}" class="pm-race-button justify-center">{{ $it ? 'Apri workspace' : 'Open workspace' }}</a>
                        </div>
                    </div>
                </section>

                <section class="grid gap-4 xl:grid-cols-3">
                    <article class="pm-panel p-5 sm:p-6">
                        <div class="flex items-start justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Salute manutenzione' : 'Maintenance health' }}</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $it ? 'Richiede attenzione' : 'Needs attention' }}</h2></div><x-pitmetric.status-badge :label="$it ? 'In scadenza' : 'Due soon'" variant="warning" /></div>
                        <div class="mt-5 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-2xl font-black text-pm-danger">1</p><p class="mt-1 text-[10px] uppercase text-pm-muted">Overdue</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-2xl font-black text-pm-warning">2</p><p class="mt-1 text-[10px] uppercase text-pm-muted">Due soon</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-2xl font-black text-pm-success">2</p><p class="mt-1 text-[10px] uppercase text-pm-muted">OK</p></div></div>
                        <a href="{{ $demoUrl('maintenance') }}" class="pm-ghost-button mt-5 inline-flex">{{ $it ? 'Apri manutenzione' : 'Open maintenance' }}</a>
                    </article>
                    <article class="pm-panel p-5 sm:p-6"><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Ultima sessione' : 'Latest session' }}</p><h2 class="mt-2 text-lg font-black text-pm-text">Circuito di Busca</h2><p class="mt-2 text-sm text-pm-text-secondary">KR2 Race Kart · Race · 42 {{ $it ? 'giri' : 'laps' }}</p><p class="mt-5 font-mono text-3xl font-black text-pm-text">52.184</p><p class="mt-1 text-xs text-pm-muted">Best lap · 50,4 km</p><a href="{{ $demoUrl('sessions') }}" class="pm-ghost-button mt-5 inline-flex">{{ $it ? 'Vedi sessioni' : 'View sessions' }}</a></article>
                    <article class="pm-panel p-5 sm:p-6"><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-muted">{{ $it ? 'Costo stagione' : 'Season cost' }}</p><h2 class="mt-2 text-lg font-black text-pm-text">€ 4.018,70</h2><p class="mt-2 text-sm text-pm-text-secondary">€ 2,18 / km · 31 {{ $it ? 'movimenti registrati' : 'recorded entries' }}</p><div class="mt-5 h-2 overflow-hidden rounded-full bg-pm-subtle"><div class="h-full w-[64%] bg-pm-accent"></div></div><a href="{{ $demoUrl('expenses') }}" class="pm-ghost-button mt-5 inline-flex">{{ $it ? 'Apri costi' : 'Open expenses' }}</a></article>
                </section>

            @elseif ($section === 'garage')
                <section class="pm-panel p-5 sm:p-6">
                    <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                        <div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-pm-success/30 bg-pm-success-subtle px-2.5 py-1 text-[11px] font-bold tracking-[0.08em] text-pm-success">WORKSPACE</span><span class="text-xs text-pm-muted">{{ $demo['workspace']['name'] }}</span></div><p class="mt-2 max-w-3xl text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Gestisci i mezzi reali del team e ciò che è fisicamente installato su ciascuno.' : 'Manage the team vehicles and what is physically installed on each one.' }}</p></div>
                        <div class="flex items-center gap-3"><div class="rounded-xl border border-pm-border bg-pm-subtle px-4 py-3 text-right"><p class="text-[11px] font-bold uppercase tracking-[0.1em] text-pm-muted">{{ $it ? 'Mezzi' : 'Vehicles' }}</p><p class="mt-1 text-2xl font-black text-pm-text">{{ count($demo['vehicles']) }}</p></div><button class="pm-race-button opacity-50" disabled title="{{ $readonly }}">+ {{ $it ? 'Aggiungi mezzo' : 'Add vehicle' }}</button></div>
                    </div>
                </section>
                <div><h1 class="mt-2 text-2xl font-black tracking-[-0.03em] text-pm-text sm:text-3xl">{{ $it ? 'Garage mezzi' : 'Vehicle garage' }}</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Lo stesso Garage del gestionale, popolato con dati dimostrativi.' : 'The same Garage as the manager, populated with demo data.' }}</p></div>
                <div class="grid gap-5 xl:grid-cols-2">
                    @foreach ($demo['vehicles'] as $vehicle)
                        <article id="vehicle-{{ $vehicle['id'] }}" class="pm-panel group relative isolate min-h-[350px] overflow-hidden p-0 transition duration-300 hover:-translate-y-1 hover:border-pm-accent/40 hover:shadow-xl">
                            <div class="pointer-events-none absolute inset-0 overflow-hidden"><div class="absolute -left-14 top-1/2 w-[78%] -translate-y-1/2 text-pm-accent opacity-[0.14] transition duration-500 group-hover:translate-x-2 group-hover:scale-[1.03] group-hover:opacity-[0.22]"><x-pitmetric.vehicle-silhouette :type="$vehicle['category']" /></div><div class="absolute inset-0 bg-gradient-to-r from-transparent via-pm-page/25 to-pm-page/90"></div><div class="absolute inset-x-0 bottom-0 h-44 bg-gradient-to-t from-pm-page via-pm-page/95 to-transparent"></div></div>
                            <div class="relative z-10 flex min-h-[350px] flex-col p-5 sm:p-6">
                                <div class="flex items-start justify-between gap-4"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-pm-border bg-pm-subtle/90 px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-pm-muted">{{ $vehicle['category'] }}</span><span class="rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.1em] {{ $vehicle['status'] === 'active' ? 'bg-pm-success-subtle text-pm-success' : 'bg-pm-subtle text-pm-muted' }}">{{ $vehicle['status'] }}</span><span class="rounded-full border border-pm-border bg-pm-page/70 px-2.5 py-1 text-[10px] font-bold text-pm-muted">{{ count($vehicle['parts']) }} {{ $it ? 'pezzi' : 'parts' }}</span></div><span class="rounded-lg border border-pm-border bg-pm-page/75 px-2.5 py-1.5 font-mono text-[11px] font-bold text-pm-muted">#{{ $vehicle['id'] }}</span></div>
                                <div class="mt-10 md:ml-[34%]"><h2 class="text-2xl font-black tracking-[-0.035em] text-pm-text sm:text-3xl">{{ $vehicle['name'] }}</h2><p class="mt-2 text-sm font-semibold text-pm-text-secondary">{{ $vehicle['manufacturer'] }} {{ $vehicle['model'] }} · {{ $vehicle['year'] }}</p><p class="mt-2 font-mono text-xs text-pm-muted">{{ $vehicle['identifier'] }}</p><p class="mt-3 max-w-xl text-sm leading-6 text-pm-text-secondary">{{ $vehicle['notes'] }}</p></div>
                                <div class="mt-auto pt-8"><div class="flex items-end justify-between gap-3 border-t border-pm-border/80 pt-4"><div><p class="text-[10px] font-black uppercase tracking-[0.14em] text-pm-accent">{{ $it ? 'Componenti montati' : 'Installed components' }}</p><p class="mt-1 hidden text-xs text-pm-muted md:block">{{ $it ? 'Apri Componenti per vedere utilizzo e dettagli.' : 'Open Components to inspect usage and details.' }}</p></div><div class="flex shrink-0 gap-2"><button class="pm-ghost-button opacity-45" disabled>{{ $it ? 'Modifica' : 'Edit' }}</button><button class="pm-danger-button opacity-45" disabled>{{ $it ? 'Archivia' : 'Archive' }}</button></div></div><div class="mt-3 grid max-h-28 gap-2 overflow-y-auto pr-1 sm:grid-cols-2">@foreach ($vehicle['parts'] as $part)<a href="{{ $demoUrl('components') }}" class="rounded-xl border border-pm-border bg-pm-page/80 px-3 py-2.5 transition hover:border-pm-accent/50 hover:bg-pm-accent/5"><span class="truncate text-sm font-black text-pm-text">{{ $part }}</span><p class="mt-1 text-[11px] text-pm-muted">{{ $it ? 'Montato · tracciato' : 'Installed · tracked' }}</p></a>@endforeach</div></div>
                            </div>
                        </article>
                    @endforeach
                </div>

            @elseif ($section === 'components')
                <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><x-pitmetric.page-header :title="$it ? 'Componenti reali' : 'Real components'" :description="$it ? 'Componenti, contatori di utilizzo e installazioni sui mezzi.' : 'Components, usage counters and vehicle installations.'" /><div class="flex flex-wrap gap-2"><button class="pm-race-button opacity-50" disabled>+ {{ $it ? 'Componente' : 'Component' }}</button><button class="pm-ghost-button opacity-50" disabled>{{ $it ? 'Monta componente' : 'Install component' }}</button></div></div>
                <section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table data-pm-responsive-table class="w-full min-w-[1180px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">{{ $it ? 'Componente' : 'Component' }}</th><th class="px-4 py-3">{{ $it ? 'Tipo' : 'Type' }}</th><th class="px-4 py-3">{{ $it ? 'Montato su' : 'Installed on' }}</th><th class="px-4 py-3">{{ $it ? 'Metrica' : 'Metric' }}</th><th class="px-4 py-3">{{ $it ? 'Dall’ultimo service' : 'Since service' }}</th><th class="px-4 py-3">{{ $it ? 'Utilizzo totale' : 'Lifetime' }}</th><th class="px-4 py-3">{{ $it ? 'Acquisto' : 'Purchase' }}</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['components'] as $part)<tr><td class="px-4 py-4"><p class="font-bold text-pm-text">{{ $part['name'] }}</p><p class="mt-1 text-xs text-pm-muted">{{ $part['serial'] }}</p></td><td class="px-4 py-4 text-pm-text-secondary">{{ $part['type'] }}</td><td class="px-4 py-4"><a href="{{ $demoUrl('garage') }}" class="font-bold text-pm-accent">{{ $part['vehicle'] }}</a><p class="mt-1 text-xs text-pm-muted">{{ $part['position'] }} · 18/09/2026</p></td><td class="px-4 py-4 text-pm-text-secondary">{{ $part['metric'] }}</td><td class="px-4 py-4 font-mono text-pm-text">{{ $part['since'] }}</td><td class="px-4 py-4 font-mono text-pm-text">{{ $part['lifetime'] }}</td><td class="px-4 py-4 font-mono font-bold text-pm-text">{{ $part['purchase'] }}</td><td class="px-4 py-4 text-right"><button class="pm-ghost-button opacity-45" disabled>{{ $it ? 'Modifica' : 'Edit' }}</button></td></tr>@endforeach</tbody></table></div></section>

            @else
                @php
                    $descriptions = [
                        'events' => $it ? 'Weekend gara, entry, task e attività in pista.' : 'Race weekends, entries, tasks and track activity.',
                        'sessions' => $it ? 'Sessioni finalizzate e utilizzo propagato ai componenti.' : 'Finalized sessions and usage propagated to components.',
                        'circuits' => $it ? 'Circuiti e layout utilizzati dalle sessioni.' : 'Circuits and layouts used by sessions.',
                        'configurations' => $it ? 'Versioni della build fisica dei mezzi.' : 'Versioned snapshots of each physical vehicle build.',
                        'setups' => $it ? 'Assetti tecnici salvati e collegati a mezzo e circuito.' : 'Saved technical setups linked to vehicle and circuit.',
                        'maintenance' => $it ? 'Scadenze, stato e storico degli interventi.' : 'Schedules, status and service history.',
                        'timing' => $it ? 'Tempi giro e settori delle sessioni.' : 'Lap and sector timing from sessions.',
                        'telemetry' => $it ? 'Riepilogo dei dati telemetrici importati.' : 'Summary of imported telemetry data.',
                        'insights' => $it ? 'Indicatori sintetici sul weekend e sulla salute tecnica.' : 'Summary indicators for weekend and technical health.',
                        'expenses' => $it ? 'Costi operativi e storico economico del team.' : 'Operating costs and team financial history.',
                        'team' => $it ? 'Membri, ruoli e accesso al workspace.' : 'Members, roles and workspace access.',
                    ];
                @endphp
                <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><x-pitmetric.page-header :title="$title" :description="$descriptions[$section] ?? ''" /><div class="flex flex-wrap gap-2"><button class="pm-race-button opacity-50" disabled title="{{ $readonly }}">+ {{ $it ? 'Nuovo' : 'New' }}</button><button class="pm-ghost-button opacity-50" disabled>{{ $it ? 'Modifica' : 'Edit' }}</button></div></div>

                @if ($section === 'events')
                    <div class="grid gap-4 xl:grid-cols-2">@foreach ($demo['events'] as $event)<article class="pm-panel p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-[11px] font-bold uppercase tracking-[0.12em] text-pm-accent">RACE WEEKEND</p><h2 class="mt-2 text-xl font-black text-pm-text">{{ $event['name'] }}</h2><p class="mt-2 text-sm text-pm-text-secondary">{{ $event['date'] }} · {{ $event['circuit'] }}</p></div><x-pitmetric.status-badge :label="$event['status']" :variant="$event['status'] === 'active' ? 'success' : ($event['status'] === 'planned' ? 'warning' : 'neutral')" /></div><div class="mt-5 grid grid-cols-3 gap-2 text-center"><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">{{ $event['entries'] }}</p><p class="text-[10px] uppercase text-pm-muted">Entries</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">{{ $event['sessions'] }}</p><p class="text-[10px] uppercase text-pm-muted">Sessions</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">{{ $event['tasks'] }}</p><p class="text-[10px] uppercase text-pm-muted">Tasks</p></div></div></article>@endforeach</div>
                @elseif ($section === 'sessions')
                    <section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[980px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">{{ $it ? 'Data' : 'Date' }}</th><th class="px-4 py-3">Event</th><th class="px-4 py-3">{{ $it ? 'Mezzo' : 'Vehicle' }}</th><th class="px-4 py-3">{{ $it ? 'Circuito' : 'Circuit' }}</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Laps</th><th class="px-4 py-3">Best</th><th class="px-4 py-3">{{ $it ? 'Distanza' : 'Distance' }}</th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['sessions'] as $row)<tr><td class="px-4 py-4 text-pm-muted">{{ $row['date'] }}</td><td class="px-4 py-4 font-bold text-pm-text">{{ $row['event'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['vehicle'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['circuit'] }}</td><td class="px-4 py-4">{{ $row['type'] }}</td><td class="px-4 py-4 font-mono">{{ $row['laps'] }}</td><td class="px-4 py-4 font-mono font-bold text-pm-text">{{ $row['best'] }}</td><td class="px-4 py-4 font-mono">{{ $row['distance'] }}</td></tr>@endforeach</tbody></table></div></section>
                @elseif ($section === 'circuits')
                    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach ($demo['circuits'] as $circuit)<article class="pm-panel p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-[10px] font-black uppercase tracking-[0.12em] text-pm-accent">CIRCUIT</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $circuit['name'] }}</h2><p class="mt-1 text-sm text-pm-text-secondary">{{ $circuit['layout'] }}</p></div><span class="rounded-lg border border-pm-border bg-pm-subtle px-2.5 py-1.5 font-mono text-xs text-pm-muted">{{ $circuit['length'] }}</span></div><div class="mt-5 grid grid-cols-2 gap-2"><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="text-xl font-black text-pm-text">{{ $circuit['sessions'] }}</p><p class="text-[10px] uppercase text-pm-muted">Sessions</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><p class="font-mono text-xl font-black text-pm-text">{{ $circuit['best'] }}</p><p class="text-[10px] uppercase text-pm-muted">Best</p></div></div></article>@endforeach</div>
                @elseif ($section === 'configurations')
                    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach ($demo['configurations'] as $config)<article class="pm-panel p-5"><div class="flex justify-between gap-3"><div><p class="text-xs font-bold text-pm-accent">v{{ $config['version'] }}</p><h2 class="mt-1 text-lg font-black text-pm-text">{{ $config['name'] }}</h2><p class="mt-2 text-sm text-pm-text-secondary">{{ $config['vehicle'] }}</p></div><span class="text-xs text-pm-muted">{{ $config['updated'] }}</span></div><div class="mt-5 border-t border-pm-border pt-4 text-sm text-pm-muted">{{ $config['parts'] }} {{ $it ? 'componenti installati' : 'installed components' }}</div></article>@endforeach</div>
                @elseif ($section === 'setups')
                    <div class="grid gap-4 lg:grid-cols-3">@foreach ($demo['setups'] as $setup)<article class="pm-panel p-5"><p class="text-[10px] font-black uppercase tracking-[0.12em] text-pm-accent">SETUP</p><h2 class="mt-2 text-lg font-black text-pm-text">{{ $setup['name'] }}</h2><p class="mt-1 text-sm text-pm-text-secondary">{{ $setup['vehicle'] }} · {{ $setup['track'] }}</p><dl class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><dt class="text-xs text-pm-muted">Tyres</dt><dd class="mt-1 font-mono text-pm-text">{{ $setup['tyres'] }}</dd></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-3"><dt class="text-xs text-pm-muted">Gear</dt><dd class="mt-1 font-mono text-pm-text">{{ $setup['gear'] }}</dd></div></dl></article>@endforeach</div>
                @elseif ($section === 'maintenance')
                    <section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">{{ $it ? 'Componente' : 'Component' }}</th><th class="px-4 py-3">{{ $it ? 'Intervento' : 'Service' }}</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">{{ $it ? 'Scadenza' : 'Due' }}</th><th class="px-4 py-3">{{ $it ? 'Ultimo service' : 'Last service' }}</th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['maintenance'] as $row)<tr><td class="px-4 py-4 font-bold text-pm-text">{{ $row['component'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['title'] }}</td><td class="px-4 py-4"><x-pitmetric.status-badge :label="$row['status']" :variant="$row['status'] === 'overdue' ? 'danger' : ($row['status'] === 'due_soon' ? 'warning' : 'success')" /></td><td class="px-4 py-4 font-mono text-pm-text">{{ $row['due'] }}</td><td class="px-4 py-4 text-pm-muted">{{ $row['last'] }}</td></tr>@endforeach</tbody></table></div></section>
                @elseif ($section === 'timing')
                    <section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">Driver</th><th class="px-4 py-3">Session</th><th class="px-4 py-3">Lap</th><th class="px-4 py-3">Time</th><th class="px-4 py-3">S1</th><th class="px-4 py-3">S2</th><th class="px-4 py-3">S3</th><th class="px-4 py-3">Delta</th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['timing'] as $row)<tr><td class="px-4 py-4 font-bold text-pm-text">{{ $row['driver'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['session'] }}</td><td class="px-4 py-4 font-mono">{{ $row['lap'] }}</td><td class="px-4 py-4 font-mono font-black text-pm-text">{{ $row['time'] }}</td><td class="px-4 py-4 font-mono">{{ $row['s1'] }}</td><td class="px-4 py-4 font-mono">{{ $row['s2'] }}</td><td class="px-4 py-4 font-mono">{{ $row['s3'] }}</td><td class="px-4 py-4 font-mono text-pm-accent">{{ $row['delta'] }}</td></tr>@endforeach</tbody></table></div></section>
                @elseif ($section === 'telemetry')
                    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach ($demo['telemetry'] as $metric)<article class="pm-stat-card"><p class="text-[11px] font-semibold uppercase tracking-[0.12em] text-pm-muted">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-black text-pm-text">{{ $metric['value'] }}</p><p class="mt-2 text-xs text-pm-muted">{{ $metric['note'] }}</p></article>@endforeach</section><section class="pm-panel p-5 sm:p-6"><div class="flex items-center justify-between gap-4"><div><p class="text-[11px] font-black uppercase tracking-[0.12em] text-pm-accent">TELEMETRY IMPORT</p><h2 class="mt-2 text-xl font-black text-pm-text">Busca Qualifying · Lap 14</h2><p class="mt-2 text-sm text-pm-text-secondary">Rotax MAX EVO #02 · KR2 Race Kart · 51.992</p></div><button class="pm-race-button opacity-50" disabled>{{ $it ? 'Importa file' : 'Import file' }}</button></div><div class="mt-6 grid h-56 place-items-center rounded-xl border border-pm-border bg-pm-subtle"><div class="text-center"><p class="font-mono text-4xl font-black text-pm-accent">112.8</p><p class="mt-2 text-xs uppercase tracking-[0.12em] text-pm-muted">km/h · demo trace preview</p></div></div></section>
                @elseif ($section === 'insights')
                    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">Best lap</p><p class="mt-3 font-mono text-2xl font-black text-pm-text">51.992</p><p class="mt-2 text-xs text-pm-success">-0.619 vs previous</p></article><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">Consistency</p><p class="mt-3 text-2xl font-black text-pm-text">92%</p><p class="mt-2 text-xs text-pm-muted">Top 10 laps</p></article><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">Maintenance risk</p><p class="mt-3 text-2xl font-black text-pm-warning">2</p><p class="mt-2 text-xs text-pm-muted">Due soon</p></article><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">Weekend cost</p><p class="mt-3 text-2xl font-black text-pm-text">€ 561,40</p><p class="mt-2 text-xs text-pm-muted">Busca Race Weekend</p></article></section><section class="pm-panel p-5 sm:p-6"><p class="text-[11px] font-black uppercase tracking-[0.12em] text-pm-accent">WEEKEND REPORT</p><h2 class="mt-2 text-xl font-black text-pm-text">{{ $it ? 'Sintesi operativa' : 'Operational summary' }}</h2><div class="mt-5 grid gap-3 md:grid-cols-3"><div class="rounded-xl border border-pm-border bg-pm-subtle p-4"><p class="font-bold text-pm-text">{{ $it ? 'Prestazione' : 'Performance' }}</p><p class="mt-2 text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Qualifica più veloce di 0,619 s rispetto al riferimento precedente.' : 'Qualifying improved by 0.619 s versus the previous reference.' }}</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-4"><p class="font-bold text-pm-text">{{ $it ? 'Affidabilità' : 'Reliability' }}</p><p class="mt-2 text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Catena e top-end motore sono le prossime priorità.' : 'Chain and engine top-end are the next priorities.' }}</p></div><div class="rounded-xl border border-pm-border bg-pm-subtle p-4"><p class="font-bold text-pm-text">{{ $it ? 'Costi' : 'Costs' }}</p><p class="mt-2 text-sm leading-6 text-pm-text-secondary">{{ $it ? 'Pista e carburante rappresentano il 45% del weekend.' : 'Track and fuel represent 45% of weekend spend.' }}</p></div></div></section>
                @elseif ($section === 'expenses')
                    <section class="grid gap-3 sm:grid-cols-3"><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">{{ $it ? 'Stagione' : 'Season' }}</p><p class="mt-3 text-2xl font-black text-pm-text">€ 4.018,70</p></article><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">{{ $it ? 'Questo mese' : 'This month' }}</p><p class="mt-3 text-2xl font-black text-pm-text">€ 1.179,30</p></article><article class="pm-stat-card"><p class="text-[11px] uppercase text-pm-muted">Cost / km</p><p class="mt-3 text-2xl font-black text-pm-text">€ 2,18</p></article></section><section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">{{ $it ? 'Data' : 'Date' }}</th><th class="px-4 py-3">{{ $it ? 'Categoria' : 'Category' }}</th><th class="px-4 py-3">{{ $it ? 'Mezzo' : 'Vehicle' }}</th><th class="px-4 py-3">{{ $it ? 'Nota' : 'Note' }}</th><th class="px-4 py-3 text-right">{{ $it ? 'Importo' : 'Amount' }}</th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['expenses'] as $row)<tr><td class="px-4 py-4 text-pm-muted">{{ $row['date'] }}</td><td class="px-4 py-4 font-bold text-pm-text">{{ $row['category'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['vehicle'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $row['note'] }}</td><td class="px-4 py-4 text-right font-mono font-bold text-pm-text">{{ $row['amount'] }}</td></tr>@endforeach</tbody></table></div></section>
                @elseif ($section === 'team')
                    <section class="pm-panel p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[11px] font-black uppercase tracking-[0.12em] text-pm-accent">WORKSPACE</p><h2 class="mt-2 text-xl font-black text-pm-text">Race Team Demo</h2><p class="mt-2 text-sm text-pm-text-secondary">Manager · 3 members</p></div><button class="pm-race-button opacity-50" disabled>{{ $it ? 'Invita membro' : 'Invite member' }}</button></div></section><section class="pm-panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="border-b border-pm-border bg-pm-subtle text-[11px] uppercase tracking-[0.1em] text-pm-muted"><tr><th class="px-4 py-3">Name</th><th class="px-4 py-3">Email</th><th class="px-4 py-3">Role</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-pm-border">@foreach ($demo['members'] as $member)<tr><td class="px-4 py-4 font-bold text-pm-text">{{ $member['name'] }}</td><td class="px-4 py-4 text-pm-text-secondary">{{ $member['email'] }}</td><td class="px-4 py-4">{{ $member['role'] }}</td><td class="px-4 py-4"><x-pitmetric.status-badge :label="$member['status']" variant="success" /></td></tr>@endforeach</tbody></table></div></section>
                @endif
            @endif
        </div>
    </div>
</x-layouts::app_demo>
